version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "brandub-game"
      POSTGRES_USER: "erentsen"
      POSTGRES_PASSWORD: "ujn147dgkj"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
